### ISSUE TITLE
Repository name is not great

### ISSUE THREAD

**Issue by brycelelbach** [executors/executors#156]
Are we planning on having a separate repo for the proposal for each meeting?

If not, we should probably bite the bullet now and rename this repo; I anticipate we'll continue using it going forward, so we should make sure it has a proper name. P0443 for example.

**Comment by jaredhoberock** [comment]
No, we don't plan to have a separate repository for each committee meeting.

I agree that the current name of the repository is no longer very meaningful. Rather than using the paper number, I'd suggest something straightforward like `executors` or `executors_core_proposal`, since not many folks track proposals at that level of detail.

**Comment by jaredhoberock** [comment]
I just went with "executors" -- it's at least an improvement over
