### ISSUE TITLE
Mixing of blocking semantics and directionality in `two-way synchronous`

### ISSUE THREAD

**Issue by AerialMantis** [executors/executors#161]
An issue that I encountered when writing up the generalisation of executors was that there was a combination of the execution properties which would not work together. The `two-way synchronous` directionality is not compatible with the `non-blocking`  blocking semantics, meaning that for this combination there has to be an exception to the rules.

I think the issue is, and I believe this was also raised in the feedback at the SG1 meeting is that the `two-way synchronous` directionality property also contains blocking semantics properties.

I think a possible solution to this could be to remove the distinction between `two-way synchronous` and `two-way asynchronous` and have the directionality property specify only that a return channel is used, and then have the type of that return channel determined by the blocking semantics.

So for example a `non-blocking` `two-way executor` would has the execution function `future_t<R> async_execute(...)` since it is asynchronous and a `potentially blocking` `two-way executor` would have the execution function `R sync_execute(...)` since it may potentially block.

An executor category would still be capable of providing both of these execution functions if necessary, but this would simplify the executor properties and remove the need for the exception to the rules.

What does everyone think would this work, or would there be issues with this simplification?

**Comment by AerialMantis** [comment]
After discussing this on the call we agreed that `sync_execute()` would have to return `future_t<R>` as it's potentially non-blocking, and his could potentially work if `future_t` be a light weight future type where the value can be immediately ready in the case of blocking.

**Comment by LeeHowes** [comment]
I'm not sure I understand how sync_execute can be non-blocking. 

This is not enough though:
So for example a non-blocking two-way executor would has the execution function future_t<R> async_execute(...) since it is asynchronous and a potentially blocking two-way executor would have the execution function R sync_execute(...) since it may potentially block.

I would suggest that a synchronous operation guarantees blocking by definition. An asynchronous operation merely does not guarantee non-blocking, by default. The post/defer add that guarantee.

**Comment by LeeHowes** [comment]
I'd actually like to see more of a breakdown of this. then_execute, then_post, then_async_execute, then_async_post and make it clear that then then_ functions are guaranteed not to block the caller, and depending on the definition may or may not be guaranteed not to block the completing task.

**Comment by jaredhoberock** [comment]
Yes, I agree that `sync_` is simply an exception to the blocking rules which describe the blocking guarantee as a property of the executor type. Because `sync_` functions return the result of the computation, by definition there is no way they can execute without blocking the caller.

I also agree that the naming of `then_execute` does not suggest non-blocking. The intention was that `then_execute` would guarantee semantics similarly to `async_execute`. Both of these return a future, and they both may or may not block the caller. Also agree that our naming scheme suggests that `then_post`, `then_defer`, etc. which would make strong guarantees are holes in the API.

However, I wouldn't propose that we fill these holes right now because I don't think proliferating additional execution functions will increase consensus within SG1. It would be a good idea to note these inconsistencies in the design document, though.

**Comment by LeeHowes** [comment]
No, we need not fill the holes right now. Adding then_async_ is probably noise too, given that there is probably no useful sync form here.

Can we at least make it clear that the blocking semantics defined by the trait apply to then_execute, and precisely where they apply: I would suggest that if the executor guarantees no blocking then both the completing task and the caller of then_execute are guaranteed to block. If it does not, then neither is.

**Comment by AerialMantis** [comment]
I agree that `sync_execute` must always be blocking in it's current form, as it returns the result by value.

Though I think the way blocking semantics are currently represented in execution functions could be confusing and part of that is because we represent blocking semantics via the base function name; `execute`, `post` and `defer`, but have `sync_execute` as a special case of directionality that overrides the blocking semantics with always blocking.

A potential solution to this could be to introduce an execution function with always blocking semantics such as `invoke` that is derived from the blocking semantics property rather than the directionality property as `sync_execute` is now. This would mean that both one-way and two-way directionality could be combined with all forms of blocking semantics so there would be no need for an exception rule. It also adds a execution function for a currently unspecified case: one-way always blocking.


one-way possibly blocking - `void execute(...)`
one-way non-blocking - `void post(...)` & `void defer(...)`
one-way always blocking - `invoke(...)`

two-way possibly blocking - `future_t<R> async_execute(...)`
two-way non-blocking - `future_t<R> async_post(...)` & `future_t<R> async_defer(...)`
two-way always blocking - `R async_invoke(...)`

The only changes to the existing execution functions this would introduce would be to add a new execution function called `invoke` which behaves the same as `execute` but is guaranteed to block, and the existing execution function `sync_execute` would become `async_invoke`. Though this naming is not ideal as it

**Comment by LeeHowes** [comment]
Is the use case of wanting a function that is guaranteed to block, and yet which you want to run on an executor rather than inline very common?

At the moment everything is asynchronous unless you want a result back, with some functions guaranteeing that they won't mess up my main thread (or function executing on the executor) by blocking it and deadlocking my system. I don't really see the use case for a function for which I do not care about the return value, but do care that I wait for it to complete. It would just conflate with the future<void> case which solves this fairly well.

**Comment by AerialMantis** [comment]
Admittedly the use case for a one-way always blocking executor is not as great as other execution functions, though I believe there may still be a case for it. You may wish to for example execute a function where there is no return value, but you instead return your result via an object captured by the function, and you want to wait for the execution to complete immediately.

There currently doesn't appear to be a way to achieve this without using a synchronous two-way executor and then discarding the result, or perhaps waiting on the execution context.

By moving the always blocking semantics to be associated with the blocking semantics property as apposed to the directionality property I also think it would make the mapping of properties to execution functions more consistent and easier to understand, removing the need for the `sync_execute` exception.

**Comment by LeeHowes** [comment]
Would you implement it that way, though? The usual way, and the reason that that one-way is the more general approach for most of us, is by embedding a promise in the task. 
Promise p<int>;
auto f = p.getFuture();
exec.execute([=, p= std::move(p)](){
   // Do stuff
   p.setValue(some result);
});
f.wait();

Or use a two_way version with a void future, of course.

**Comment by AerialMantis** [comment]
It could be implemented this way, however this would require that `exec` be a host based executor where direct communication between the execution agent which calls the function and the caller is possible in order for the promise to be set. If `exec` executes work on a remote device such as a GPU then this will not necessarily be possible.

**Comment by hcedwar** [comment]
During May 26 telecon an off-hand comment was made by Chris K that he would never need to mix one-way and two-way execution (within a capability / system ?).
A thought percolated during the telecon - should one-way vs. two-way be a property of an executor?  This would be in the direction of Jared's simplified executor idea.

**Comment by jaredhoberock** [comment]
I think the properties scheme has resolved these issues.
