### ISSUE TITLE
Consider whether to provide a one-way blocking execution function

### ISSUE THREAD

**Issue by chriskohlhoff** [executors/executors#190]
We should consider whether to include a one-way synchronous (i.e. always blocking) execution function, or at least document why we do not do so.

Reasons to consider including this function:

* It fills a hole in the possible combinations of directionality and blocking semantics.

* It allows an executor to advertise that it supports always-blocking semantics, and allows a user to test for and choose those semantics at compile time.

* It provides different semantics than `sync_execute`, in that it decouples waiting for completion from delivery of the result. In particular, (depending on the resolution of #189) any exception thrown by the submitted function will be delivered via the execution context's "back channel". This may be important when executing code on, say, a remote node: arbitrary exception types cannot always be serialised and transported back to the caller.

**Comment by chriskohlhoff** [comment]
@AerialMantis, I think you had some points to add here?

**Comment by AerialMantis** [comment]
Thanks Chris, this summarises the points I was trying to make really well as well.

So I had two reasons why I thought it would be a good idea to provide a one-way always blocking execution function.

The first is that there seems to a mixing of the directionality property and the blocking semantics property in mapping the properties to execution functions when it comes to `sync_execute`. The general pattern appears to be that the `*execute` execution functions are produced by the `possibly blocking` blocking semantics guarantee then whether or not it blocks is determined by the `executor_execute_blocking_category` trait, and the non-`*execute` execution functions are produced by the other blocking semantics guarantees, such as the `*post` and `*defer` execution functions. But `sync_execute` is an exception to this pattern as it is an `*execute` function but is produced by the `two-way` directionality variant and enforces blocking semantics which conflicts with the blocking semantics guarantee. This is essentially a design issue, but I believe that as executors are likely to be a complex interface with a potentially a large number of execution functions we should try to keep the mapping of properties to execution functions simple and symmetrical, without any special rules, as to make it easier to understand, and without this function there seems to be a gap. I proposed a refactoring of the execution functions that would include a one-way always blocking function in #161. Even if we decide not to include a one-way always blocking execution function we may still want to consider refactoring the execution functions so that the mapping is clearer.

The second is that by not providing an always blocking one-way execution function we are potentially forcing unwanted semantics in the case where this is what the user wants. For example, if a user wants an always blocking executor then the only option at the moment is `sync_execute` which enforces a return channel and potentially alters the way in which exceptions are handled (depending on the outcome of #189). Or if a user wants a one-way executor then the only way currently to guarantee always blocking semantics is to use an executor where `executor_execute_blocking_category` is the always blocking guarantee. By providing an always blocking one-way execution function we can decouple the semantics of the directionality property from the semantics of the blocking semantics property.

A one-way always blocking execution function could be useful in a case where a user wants to execute work but block the caller until completion. This can be useful if a user wishes to simply send a signal or message to a remote device where they are not interested in a return channel but want to wait for it to finish immediately. Another use case of when this would be useful is if a user is passing and returning all of their variables as lambda captures, this is a typical approach in many programming models such as SYCL.

**Comment by jaredhoberock** [comment]
`oneway` + `always_blocking` supports this use case.
