### ISSUE TITLE
Should we add an execution resource that supports bulk execute and the networking TS

### ISSUE THREAD

**Issue by fraggamuffin** [executors/executors#21]
We (Gordon and I ) realize this is suppose to be minimal, and that we added thread pool resource support because everyone wants it, but we wonder if we can also add an execution resource that supports bulk execute.
Rationale: the execute functions for these are being included in the minimal paper so  it make sense to also include the execution resource that is associated with them. This doesn't have to be particularly complex definition, but we believe we should provide something like this as base for future work.

More detail available on request.

We can also add a separate resource for the Networking TS.

**Comment by mjgarland** [comment]
What kind of resource do you have in mind?  Note that thread pools can already support bulk execution; all of the bulk agents can be mapped by an executor onto one or more threads of a thread pool.

I'm personally inclined to put additional execution resources in a separate paper.

**Comment by AerialMantis** [comment]
The execution resource I had in mind was something that would be designed to support the bulk_*_execute() functions, the primary difference would be that the sub executor class defined within the resource would have bulk_execute(), bulk_async_execute() and bulk_then_execute(). Another difference would be that instead of the attach() member function you would have a wait() member function that would essentially wait for all asynchronous execution agents to finish, though observably this behaviour would be similar to that of attach().

However if the intention is that the thread_pool support the bulk_*_execute() functions as well then I believe that the thread_pool would solve this purpose providing the basic_executor can be specialised, removing the need for an additional resource, which I believe would be preferable for the minimal paper.

Though I would suggest that we consider altering the name of the resource to agent_pool instead to align with the convention of executors executing light weight execution agents?

**Comment by fraggamuffin** [comment]
It looks like in the last call that @chriskohlhoff would add bulk_*_execute()? There is also a wait function? This seems to solve one part of this.  
So only the agent_pool resource naming remains an issue as thread_pool seems to denote std::threads.

**Comment by jaredhoberock** [comment]
This issue has been resolved -- `static_thread_pool`'s executor is a bulk executor.
