### ISSUE TITLE
When multiple execution functions are passed to async

### ISSUE THREAD

**Issue by fraggamuffin** [executors/executors#22]
What is the expected behaviour of std::async() if you were to pass it an executor with multiple execution functions for example (one-way-can-block, one-way-never-block & two-way-can-block). My understanding of the discussion the previous call is that std::async() would assume the properties of the executor it is provided, but in this case which execute function would an implementation be expected to choose or could it choose any? This may not be what we want, if we were to pass the executor of the networking TS to std::async() it would be fee to choose any execute function.

**Comment by mjgarland** [comment]
The behavior embodied in the current draft paper is to specify that std::async() would call a specific customization point, namely execution::async_execute().  The default implementation of that customization point should call the corresponding method on the executor, while leaving open the possibility of customizing its behavior for the specific type.  Does that seem like a reasonable solution?

**Comment by AerialMantis** [comment]
Yes, this mechanism of having the control structure call a specific customisation point that can then be specialised depending on the executor type sounds like a good solution, I do have a couple of thoughts about it though.

My interpretation of this is that the naming of the customisation points suggest they are tightly coupled with the execute functions of the different executor categories; so in the case of async() calling execution::async_execute() this suggests the default behaviour of async() is that of the TwoWayExecutor category, however in the previous call I believe we started moving towards the direction of having async() be more generic, adopting the behaviour of the executor type that it's passed rather than having a set behaviour that can be emulated. If we were to go this route I would suggest the customisation points be altered to associate instead with the control structures so async() would call a customisation point called something like execution::async(), which could then be specialised by the executor type as currently defined, this way it would be clearer that the behaviour is based on the executor type.

My second thought, which I apologise may be out of scope of the minimal paper, would an implementation of async() and an implementation of an executor and specialisation of the customisation point necessarily have to be from the same vendor, because it seams like this mechanism supports inter-op ability between executor implementations, was this the intention?

**Comment by jaredhoberock** [comment]
The current thinking is that `std::async` would do something like `execution::require(ex, execution::twoway).twoway_execute()`.
