### ISSUE TITLE
Feedback from CppCon talk

### ISSUE THREAD

**Issue by AerialMantis** [executors/executors#265]
I presented the current executors proposal at CppCon last week. The talk was very well received and there were a lot of interesting questions. Most of them I was able to answer with the current design, however there are a few that we either don't address or i'm not aware of how we address them.

* What is the lifetime expectations of an executor in relation to an execution context, do we require that an execution contexts outlives an executors created from it? Though this is perhaps a question for the separate execution context paper, I will post this same question there.
* Is it possible to perform a `require` on a polymorphic executor? I would expect not as you cannot guarantee the capabilities of it at compile-time. If this is the case then this means that you cannot call `std::async` with a polymorphic executor as in order to guarantee the properties of `std::async` the implementation will call `require` on the executor provided to it. There was some concern about having an interface where you couldn't pass a polymorphic executor to `std::async`.

**Comment by ccmysen** [comment]
Following up on these.

- For the first one, i can't find any reference in the papers about whether the execution context necessarily outlives the executor created from it. That said, the static_thread_pool returns a reference, so we have no way of verifying the liveness of the context if it's already dead unless we explicitly create some sort of a shared state like futures to enable the ability to communicate the liveness of the underlying execution context (otherwise you potentially keep submitting work to the executor). Will find a place to sneak in some wording...
- Think we already covered `require` in the meeting, but this should be fine. Note that i think we _can_ make prefer-like functions work more generically in the polymorphic executors if we actually allow `prefer`rable traits to derive from a generic base class (such that even unsupported features being preferred would automatically default to nothing). Such an approach doesn't work for `require` though.
