### ISSUE TITLE
Consistency of via/execute_on operations

### ISSUE THREAD

**Issue by LeeHowes** [executors/executors#372]
Adding this and a related issue on the  futures repository.

If at all possible, any operation to modify the executor underlying a Future or algorithm should be consistent if that makes sense.

We proposed .via on a future. We have discussed .on for the execution policies and algorithms. We should make the two names consistent if their semantics are consistent.

**Comment by LeeHowes** [comment]
Related: https://github.com/executors/futures/issues/4

**Comment by griwes** [comment]
Just so that we can all see this (and so I can justify my highly opinionated comment):

```
future.via(ex).then(foo);
future.on(ex).then(foo);
```

I much prefer the first case; the second seems to say the future is on the executor `ex`, while the first sounds like I'm making a "view" visible via the executor.

I don't feel this really for policies:

```
std::for_each(par_unseq.via(ex), ...);
std::for_each(par_unseq.on(ex), ...);
```

**However**, and this might be a somewhat unpopular opinion - if we can't get `policy.via(ex)`, I'd much prefer to have `policy.on(ex)` and `future.via(ex)`, over `future.on(ex)`.

**Comment by jaredhoberock** [comment]
Suppose that we have some general purpose customization point, say `execution::rebind_executor(value, ex)` whose purpose in life is to return a copy of `value` with the exception that the result's "associated executor" has been replaced with `ex`. To my mind, `.via()` and `.on()` are both sugar for this rebind operation. We've chosen different names for the sugar syntax simply because different names make more sense in the separate contexts.
