### ISSUE TITLE
Customisation point overloads for execution contexts

### ISSUE THREAD

**Issue by chriskohlhoff** [executors/executors#41]
This gives users simple access to the functionality without needing to mess around with executors directly. E.g.:

```
thread_pool tp;
execute(tp, []{ ... });
auto fut = async_execute(tp, []{ ... });
```

Something like below. May be better expressed as separate overloads distinguished by SFINAE (i.e. Remarks: This overload shall not participate...), particularly for async_execute where the return type is determined from the executor.
## Function template `execution::execute()`
1. ```
   template<class E, class Function>
   void execute(E&& e, Function&& f);
   ```
   1. _Effects:_
   - If `is_one_way_executor_v<E>` is true, calls `e.execute(std::forward<Function>(f))`;
   - Otherwise, if the type `E::executor_type` exists and `is_one_way_executor_v<typename E::executor_type>` is true, calls `e.executor().execute(std::forward<Function>(f))`;
   - Otherwise, performs `DECAY_COPY(std::forward<Function>(f))()` in a new execution agent, with the call to `DECAY_COPY()` being evaluated
     in the thread that called `execute`. Any return value is discarded.

**Comment by jaredhoberock** [comment]
Something like this seems reasonable. Essentially we just want work creation to do the right thing without a lot of fuss about coming up with an executor parameter. An alternative might be to introduce this sugar at a slightly higher level interface rather than the lower level customization point interface -- for example, `std::async` rather than `execution::async_execute`. There's currently no higher level sugared interface with `execution::execute()`'s semantics, but we could introduce one.

Also, I think we may need to give a little bit more thought about what types `E` is allowed to be. The suggested text

> Otherwise, if the type E::executor_type exists and is_one_way_executor_v<typename E::executor_type> is true, calls e.executor().execute(std::forward<Function>(f));

would allow any type at all that has a member type `::executor_type` and member function `.executor()` (and if `executor_type` fulfills some additional requirements). There may be such types which would would not want to allow as parameters to some of the executor customization points. Execution policy types may be one example.

Could you give a little bit more detail about the thinking behind including this check on `E::executor_type`?

> is_one_way_executor_v<typename E::executor_type> is true

**Comment by jaredhoberock** [comment]
This enhancement can be explored independently of P0443.
