### ISSUE TITLE
Receivers should be required to have both the value method and the error method (Future Ask 4)

### ISSUE THREAD

**Issue by brycelelbach** [executors/executors#412]
During our discussions of how to integrate ideas from P1053 and P1055 into P0443 and P1054, some concerns have been raised about how error propagation works in P0443 and P10543 today.

Today, when `(bulk_)then_execute` is called with a future that contains an error instead of a value, it will call the error method on the `FutureContinuation` it was called with, if such a method exists. Oherwise, the executor will propagate the error into the future that it returns. Likewise, if a future contains a value instead of an error, and the `FutureContinuation` has no value method, the executor will propagate the value into the future that it returns:

```
// Before (P0443 and P1054 today):
struct FutureContinuation {
  // At least one of these is required (thus it will be satisfied by a calllable):
  U operator()(T value);
  U operator()(exception_arg_t, std::exception_ptr error);
};

auto f = exec.then_execute([] { /* ... */ }, pred);
```

This places the burden of implementing error and value propagation of executor authors.

P1055 suggests that instead error and value propagation should be done in receivers (aka `FutureContinuations`). The suggestion is that receivers should always require BOTH the value and the error methods:

```
// After:
struct Receiver {
  // BOTH of these are required (NOT satisfied by `Callable`s):
  U operator()(T value);
  U operator()(exception_arg_t, std::exception_ptr error);
};

// Using P1054-style `on_value`:
auto f = exec.then_execute(on_value([] { /* ... */ }), pred);
```

It has been indicated that this is necessary to support lazy execution models.

However, this has the notable downside of prohibiting users from passing simple callables directly to `(bulk_)then_execute`, which is allowed today (although, admittedly, execution functions are not intended to be a user facing interface).

Note that this would apply to all execution functions and all types of receivers if #411 (Future Ask 3) is accepted, so you would no longer be able to pass callables to `execute` and `twoway_execute`:

```
// Before (P0443 and P1054 with #411):
// `execute` takes:
struct VoidNoneReceiver {
  // At least one of these is required (satisfied by `Callable`s):
  void operator()();
  void operator()(exception_arg_t, std::exception_ptr error);
};
// `twoway_execute` takes:
struct NoneReceiver {
  // At least one of these is required (satisfied by `Callable`s):
  U operator()();
  U operator()(exception_arg_t, std::exception_ptr error);
};

exec.execute([] { /* ... */ });
auto f = exec.twoway_execute([] { /* ... */ });


// After (P0443 and P1054 with #411):
// `execute` takes:
struct VoidNoneReceiver {
  // BOTH of these are required (NOT satisfied by `Callable`s):
  void operator()();
  void operator()(exception_arg_t, std::exception_ptr error);
};
// `twoway_execute` takes:
struct NoneReceiver {
  // BOTH of these are required (NOT satisfied by `Callable`s):
  U operator()();
  U operator()(exception_arg_t, std::exception_ptr error);
};

// Using P1054-style `on_value`:
exec.execute(on_value([] { /* ... */ }));
auto f = exec.twoway_execute(on_value([] { /* ... */ }));
```

[This was discussed during the 2018-07-13 executors phone call](https://github.com/executors/futures/blob/master/notes/meetings/2018_07_13__executors__weekly.md):
- Bryce: Presumably, P1054-style helper functions would also be added to ease construction of receivers.
- Bryce: This would mean that `(bulk_)then_execute` could no longer be passed a regular `Callable` (a lambda, etc). When combined with ask #3, this would mean ALL execution function swould no longer be passed a regular `Callable`.
- Bryce: I don't understand how this is needed for exception propagation. It just moves the burden out of the executor, to the receiver or the user of the executor.
- Lee: The error method should only be required if it's used.
- Kirk: I think it should always be required.
- Bryce: If I don't write an error method and call inline_executor::execute, should it fail to compile?
  - Lee: No
  - Kirk: Yes
- Jared: I could be okay with requiring this for then_execute.
- **Bryce: What I would want is to be able to `via` the value and error method separately. I want to be able to say `via(cpu).on_error(f), via(gpu).on_value(g)`.**
- Jared: That's what I want.
- Bryce: I need some before/after examples.
- **Bryce: Does error propagation in P0443 chain properly? If it's broken we need an example of how.**

**Before this can be evaluated, some additional rationale needs to be shown. Speaking for myself, I'm unclear what the current exception propagation mechanism precludes you from doing. I would need to see a concrete "before and after" example showing the problem and how this fixes it.**

**Related Issues:**

- #411, which deals with the question of how executors should handle asynchronous system errors.
- #413, which deals with the question of whether the one-way execution function should accept receivers that expect to be passed an executor.
- #414, which deals with how we should spell the value method of work items if this ask and the two above are accepted.

**Action Items:**
- [ ] (@kirkshoop) Please provide additional rationale for this change and at least one concrete "before and after" example of something that doesn't work with P0443 exception propagation that is fixed by this change.
- [ ] (@brycelelbach) Please review the content @kirkshoop provides and give him feedback.

**Comment by brycelelbach** [comment]
[This was discussed during the 2018-07-18 futures phone call](https://github.com/executors/futures/blob/master/notes/meetings/2018_07_18__futures__weekly_us.md):
- Bryce: Right now the default is to propagate errors if no error method is required.
- Bryce: Why should we require an error method instead of defaulting to propagate.
- Kirk: If you librarize your `Receiver`s, you probably have to deal with this in one place, and you probably had to anyways.
- Mathias: It's valid to pass a `FallibleReceiver` to an `InfallibleSender`, but not vice versa.
- Bryce: Do all `Executor`s, even those that do not care about errors, have to propagate today? Do we want that requirement? Or do we want it to fail to compile?
- Mathias: I think it should fail to compile.
- Gordon, Bryce: I agree.
- **Consensus: Try out Mathias' `Fallible`/`Infallible` approach.**

**Action Items:**
- [ ] (@RedBeard0531) Please provide a rough draft of the `Fallible`/`Infallible` model you suggested, where there is a future concept for futures that only contain errors, and another type refining that which fits our traditional model of a future.
- [ ] (@brycelelbach) Assist with @RedBeard0531's task as needed.

**Comment by RedBeard0531** [comment]
https://gist.github.com/RedBeard0531/43fe750b8b0591cff9a43b6e1e517650

I wrote it up in virtual-interface style since it is what I'm more familiar with, but it should be pretty clear how it translates into concepts.

There is still a bit of handwaveyness around the return type of then(), which is intentional. It is up to each implementation what it wants to do. I can think of a few examples:

- Implementations that never deal with errors can just always return infallible futures
- Implementations can check if the sender call is noexcept
- Executors that can't handle errors can use infallible futures internally, but then go back to fallible when returning to an execution context that can. This would be implemented by propagating errors around all of the receivers that would have run on the special executor
- Implementations can offer an "assertSuccess" continuation that converts causes it to return an infallible future by aborting on errors

**Comment by LeeHowes** [comment]
> Bryce: If I don't write an error method and call inline_executor::execute, should it fail to compile?

My view on that is very specific to inline executor. In general executors are likely to want to call an error handler on a task. If they do so, and the task has no way to accept that error type, it should fail to compile.

Given that exceptions can be thrown from anywhere spontaneously, I think there is a strong argument for saying that unless code very explicitly says it is noexcept, then it could throw, catch and forward, and as such *any* execute function or task may try to propagate an exception_ptr. Given that, it is certainly safest to follow Kirk's model of requiring an exception_ptr error handler here.

I don't think we should complicate the concepts and add a whole tree of special error-free ones. It really isn't necessary and the whole goal here is to try to streamline the concepts.

**Comment by RedBeard0531** [comment]
@LeeHowes I actually disagree here. While I think most futures should be fallible, my interest in infallible futures is specifically *for executors*  (in addition to being a compromise between camps). I'm pretty sure that it isn't possible to build correct applications if executors are allowed to refuse work. I had mentioned this to you in a side conversation way back when that led to the creation of https://github.com/executors/executors/issues/373 (which seems to have never been picked up). Specifically, I'm currently thinking of the primordial executor as something with a nullary method like `LazyInfallibleFuture<void> switchTo() noexcept` where anything added to that future is *guaranteed* to run on that executor. I can't think of any way to correctly write the following program if executors are allowed to refuse work:

```cpp
// It is illegal to run follow-up callbacks inline on the FancyExecutor.
SemiFuture<Resouce> doNetworkStuffOnFancyExecutor() noexcept;

Future<void> doThing() {
    return aquireResource().then([](Resource resource1) {
        auto lk = std::lock_guard(myMutex);
        return doNetworkStuffOnFancyExecutor()
            .thenSwitchTo(myThreadPoolExecutor)
            .then([resource1](Resource resource2) mutable {
                auto lk = std::lock_guard(myMutex);
                resouce2.release();
                resouce1.release();
            }));
    });
}
```

Where should the `release()` call happen if myThreadPoolExecutor refuses to take my job? It can't run on the FancyExecutor since that breaks the rules, and it can't run inline because that would deadlock. It also can't return a errored Future since that would lead to leaking at least resource2, even if resource1 was released on both the success and error paths.

I can buy an argument that we may want to support FallibleExecutors that are allowed to refuse work, but I'd object to them being the default because they are much harder to use correctly and lay hidden traps that will almost never be exercised in testing. The only way I could see that working is if you could reserve execution prior to scheduling a job that you will cash in later and be guaranteed success. But even then, that is harder to work with for little benefit.

> the whole goal here is to try to streamline the concepts.

I don't see fewer concepts as necessarily better. We should really consider using the type system to separate things that behave substantially differently. And I think the ability to hold an error (for futures) or to handle an error (for receivers) is a substantial difference.

**Comment by LeeHowes** [comment]
I don't disagree with your fundamental point, I'm just unclear why we need any sort of infalliability for this. We have also concluded within Facebook that it is more or less impossible to build correct applications if executors are able to refuse work completely. We should apply noexcept more widely.

At the same time it is perfectly valid for an executor to tell a task not to run because it is rebalancing internally, as long as it runs that task in the expected context in some error state. It's quite reasonable then to expect the task to accept an error state - and the executor does not need to be a future that is not allowed to export such an error. 

Now allowing the executor to call set_error seems to me to be an unnecessary restriction. We can always write executors that try to refuse work, all you do is remove a way for them to let the tasks know what they are doing.

**Comment by kirkshoop** [comment]
[Elemental Concepts.pdf](https://github.com/executors/executors/files/2215029/Elemental.Concepts.pdf)
