### ISSUE TITLE
Re-expressing bulk execution via properties

### ISSUE THREAD

**Issue by brycelelbach** [executors/executors#418]
For clarity, receiver == task == continuation == the function-object like things that executors invoke.

We've spent a lot of time playing around with the idea of re-expressing bulk execution in terms of single execution interfaces that take bulk tasks.

My feeling is that as a group, we're open to exploring this further. But there are still some open questions that we need to address to help direct the design:

#### Should bulk receivers be created on and bound to a particular executors, or should they have a concrete interface (e.g. a concept or a concrete type)?

One way we could do this would be to add a `make_bulk_receiver` property, which you could use to create a bulk task on a particular executor:

```
my_executor exec;

auto bulk_receiver = query(exec, make_bulk_receiver(element_function, shape, shared_factory));
// This bulk receiver can only be consumed by `my_executor`.

exec.execute(bulk_receiver);
```

I believe the main benefits of this approach are:

* We don't add need to define a new concept/interface for bulk receivers that works for every bulk executor. Instead, executors can use whatever representation is sensible for them and the type can be opaque to users. This doesn't necessarily preclude us from adding such concepts in the future.
* Since non-bulk executors would be unable to consume bulk receivers, we don't ave to figure out how that would work.

I think there are downsides to coupling things. It means you cannot create a representation of bulk work prior to having an executor. I could imagine some higher-level libraries that might want to produce generic bulk tasks, and users of those libraries would then execute those tasks on specific executors themselves.

The alternative would be to define some concept for bulk receivers, something like:

```
struct BulkReceiver
{
  Shape shape() const;
  SharedFactory shared_factory() const;
  SingleReceiver element_receiver() const;
};
```

Where `shape` is a `Range` with arbitrary value type, `SharedFactory` is invocable with 0 arguments, and the `SingleReceiver` type returned by `element_receiver` takes a `std::tuple<typename Shape::value_type, decltype(shared_factory()())>`.

Alternatively, instead of a concept, we could create a concrete `bulk_receiver` wrapper type that all executors would use, although this may have limitations.

#### Should bulk receivers be usable with executors that don't have special support for bulk execution?

If we don't want to tie bulk receivers creation and use to a particular (bulk) executor (the latter option above), then we have to decide whether non-bulk executors can consume bulk receivers. This question basically amounts to "are bulk receivers actually receivers" (e.g. do they also satisfy `None/SingleReciever`)?

##### What are the semantics of a non-bulk executor executing a bulk receiver?

The first option would be completely sequential execution on a single execution agent, e.g.:

```
auto sf = shared_factory()();
for (auto i : shape())
  element_receiver()(std::tuple{i, s});
```

A better option might be to create N execution agents by calling the executors single execution function N times.

But, how would this work? Unless we had something like #413, where the executor is passed to the thing it is invoking, we wouldn't be able to implement this. The only method that a non-bulk executor will call on a bulk receiver is the value method, and that will be called on the execution agent that the executor has created, and as discussed in #413, that may not be the same executor. It may totally impossible for an executor to pass itself to th things it is executing in some cases.

You might be wondering if we did tie creation and use of bulk receivers to a particular executor as per the first question, would we be able to introduce some adaption/customization point to make this work for non-bulk executors? Again, the answer is probably not, unless we do something like #413. In P0443 and P1054, executors run the callables they are passed in new execution agents that they create, and it may not be possible for the executor to pass itself (or any executor other than the `inline_executor`) to the callable.

Perhaps we should explore an `execute_on` or something similar, that has semantics closer to what P1055 has in mind.

### Suggested Design

I'd suggest that we tie bulk receiver creation and use to a particular executor via a property.

**Comment by brycelelbach** [comment]
I'm not sure if this would work with the polymorphic executor. I guess `any` or `void*` would be fine; since only the executor that created it will consume it, it could presumably figure out how to unwrap it.

**Comment by brycelelbach** [comment]
I started a PR for this: #419.

**Comment by LeeHowes** [comment]
A property seems to be a fairly clunky way of implementing a customisation point overload on an executor type here. The fundamental thing you want is the type of the executor so that as much of this as possible is compile-time, because that allows you to customise your compilation for a given device.

**Comment by kirkshoop** [comment]
`BulkReceiver` does not appear to receive anything. 

methods on Receiver's take 0 or more arguments and return void.

The sender is where you add get methods - like `time_point now()`

I did an implementation of bulk_execute in the gist without impacting the concepts and it does not require get methods on the value passed to `submit()`.

**Comment by brycelelbach** [comment]
Can you clarify what you mean by a `get` method Kirk?

**Comment by brycelelbach** [comment]
> BulkReceiver does not appear to receive anything.

> methods on Receiver's take 0 or more arguments and return void.

I agree: this is why the PR doesn't use this term.

**Comment by dhollman** [comment]
```
exec.execute(bulk_receiver);
```

Isn't that just customization through overloading (i.e., `execute(BulkReceiver)` instead of customization through a named function (i.e., `bulk_execute(BulkFunction)`)? This doesn't reduce the number of execution functions or the complexity or surface area or anything, just the number of *names* for execution functions (and if that's seriously what makes the difference for LEWG, that's a really bad precedent for us to set as a committee). This is especially true if `BulkReceiver` isn't part of some broader hierarchy of receivers, which AFAICT is the case here.

**Comment by LeeHowes** [comment]
I agree, David. That's why the encodings Kirk and I have chosen hide this *inside* the task. It means that we can easily pass a task through futures and other higher level control structures and any bulkness is entirely hidden within the task. My PR made *asynchrony* change the API - but by explicitly changing the types pass through, rather than by changing the concept.

The important thing here in terms of simplification is to define the specialisations where they make sense:
 * A bulk task is still a task with an input and output, therefore if at all possible it should not change the task type.
 * An asynchronous task does have some relation to its input and output, because its output may trigger long before the work is finished.

Bryce's initial code is still workable:
```
my_executor exec;
auto bulk_receiver = query(exec, make_bulk_receiver(element_function, shape, shared_factory));
// This bulk receiver can only be consumed by `my_executor`.
exec.execute(bulk_receiver);
```
but we can pass it to *any* executor, which is what will call set_value on it and cause the bulk executor to run the work however it structured it, hidden inside the task. Which would allow:
```
my_executor exec;
my_bulk_executor bulk_exec;
auto bulk_receiver = query(bulk_exec, make_bulk_receiver(element_function, shape, shared_factory));
// This bulk receiver can only be consumed by `my_executor`.
exec.execute(bulk_receiver);
```

where the common case would be to use the same executor for both. Somewhere in a sequence of queries like this you end up approximating the customisation points I proposed.

**Comment by dhollman** [comment]
So AFAICT this means that `BulkReceiver` is part of a broader hierarchy of receivers, which is what makes this into a simplification even if the total surface area is a bit larger (in the most feature-rich bulk executor, you'd now need to have a special `BulkReceiver` as well as an `execute()` that can recognize it).  I think I'm on board with that.

**Comment by brycelelbach** [comment]
Lee,

IIUC, what you're suggesting is that "make_bulk_receiver" creates a task that enqueues bulk work, and that task itself can be invoked on any executor.

```
my_executor exec;
my_bulk_executor bulk_exec;
auto bulk_receiver = query(bulk_exec, make_bulk_receiver(element_function, shape, shared_factory));
exec.execute(bulk_receiver);
```

Yes?

Or more concretely, the type returned by `query(bulk_exec, make_bulk_receiver(element_function, shape, shared_factory))` isn't a completely opaque implementation-defined type, but it's something that satisfies the (Single) Receiver concept - e.g. something that can be passed to any executor's `execute`.

**Comment by LeeHowes** [comment]
The question is what functionality you want to expose. The way I defined this had a clear separation. An executor did two things:
1) Triggered execution. That might be delayed, but fundamentally it was about handing responsibility for running the task wrapper somewhere.
2) Acting as a tag type for a bunch of hooks that allow the task to look up how to customise itself for the place it is meant to run.

In what I just sketched we maintain that. execute is handing over execution to the executor, running in some equivalent scope to the caller, but maybe on a thread, or a thread pool, in a queue or whatever. The task itself carries an executor which it uses to look up how to run a bulk task. We can of course build any sort of task hooks this way, hiding them within the task object, without changing the basic enqueue interface.

I'm really not clear what the set of customisation points should be to define a good bulk task. I'd be very happy to agree to a separation of concerns here and dig into exactly what the customisation points should be for bulk and how this interacts with dependency management.

**Comment by AerialMantis** [comment]
I like this approach to introducing a more task-based model in general, I think will solve the issue that LEWG raised on having too many execution functions. Though I would agree with @dhollman that this is not simplifying the interface, but reduce the immediate surface area of the execution function(s).

However, I'm not too keen on the separation between the `make_bulk_executor` query and the call to `execute` both requiring the same executor. With the limited std set of receiver types, I don't see this being an immediate problem, but I feel this approach does not scale well and could hurt portability. If we are to go in this direction I would expect that once executors have standardised there will we a large number of implementation specific receiver types, and while ensuring that all receiver types are compatible with all executors is not a realistic goal, I feel we should design the interface in such a way that it lessens the onus on users to make sure they use the right executor in the right place.

I have been working on an idea, though not complete yet, where rather than having executors create receivers directly, instead they create as I believe @brycelelbach suggested an adapter object which contains everything required to create the sender/receiver. Then we have a customisation point which is implicitly called when constructing the senders/receivers which takes an executor and an adapter and creates the receiver/receiver.

```
auto ret = pipe(
    my_inline_executor{},
    bulk_twoway(f, shape, sf),
    bulk_transform(g, dhape, sf),
    get<int>()
);
```

In the example above `bulk_twoway`, `bulk_transform` and `get` would all return an adapter which is then passed to `adapt(my_inline_executor, adapter)` which returns the sender.

This removes the need to create the tasks ahead of executing them. This would also mean that we can use the `query` customisation point as we curently do in P0443 but detecting if an executor can execute a particular kind of task as apposed to having a particular execution function.

```
auto ret = pipe(
    my_inline_executor{}.require(special_bulk_twoway),
    special_bulk_twoway(f, shape, sf),
    bulk_transform(g, shape, sf),
    get<int>()
);
```

**Comment by dhollman** [comment]
> Though I would agree with @dhollman that this is not simplifying the interface, but reduce the immediate surface area of the execution function(s).

I actually said the opposite. It *is* simplifying the interface, but at the cost of *increasing* the surface area (i.e., more concepts and customization points, but more consistent/grokkable relationships between them).

**Comment by LeeHowes** [comment]
Gordon, my goal here was to explicitly decouple the executor the task function runs on, and the executor the task in the chain runs on.

If I do, as in my example:
```
        auto realthing = op::just(2.0) |
          op::async_fork([&](){return nt;}) |
          op::async_transform(workerTask) |
          op::async_transform(workerTask) |
          op::async_join() |
          op::blocking_submit(v::on_value([&](auto v) { values.push_back(std::to_string(v)); }));
```

then there is an executor running that chain of tasks. It happens to be the inline caller. I could modify that, though:
```
        auto realthing = op::just(2.0) |
          op::via([&](){return inline_executor;}) | 
          op::async_fork([&](){return nt;}) |
          op::async_transform(workerTask) |
          op::async_transform(workerTask) |
          op::async_join() |
          op::blocking_submit(v::on_value([&](auto v) { values.push_back(std::to_string(v)); }));
```

such that it passes the 2.0 to a task that is enqueued into the `inline_executor`. That task will run the *entire* chain of tasks. It is the executor that will still be running the work after the join, and would be available to any `thread_local` we wanted to put in this chain that exposed the executor.

The new thread executor (`nt`) that fork forks onto is used to pass into the tasks. It is this executor that is used by those tasks to enqueue work on to. That is, we have a CPU task here that throws a transform off into a new thread, and chains those transforms.

What you would do as an implementation detail under these futures here is always call .execute on `inline_executor` but pass a task constructor to `nt` to send those tasks across to the new thread. There are fundamentally two different execution agents at work here, and that is why the execution as a whole has two different executors.

So whether in the example we do what I showed:
```
my_executor exec;
my_bulk_executor bulk_exec;
auto bulk_receiver = query(bulk_exec, make_bulk_receiver(element_function, shape, shared_factory));
exec.execute(bulk_receiver);
```

or not submit at all, and call inline in the current execution context:
```
my_bulk_executor bulk_exec;
auto bulk_receiver = query(bulk_exec, make_bulk_receiver(element_function, shape, shared_factory));
execute(bulk_receiver);
```

or something like that, there are still two contexts at work. The current context might call inline, it might start a thread that fires the work off sideways.
