### ISSUE TITLE
execution::mapping.thread includes things like fibers and SIMD lanes

### ISSUE THREAD

**Issue by jaredhoberock** [executors/executors#430]
`execution::mapping.thread`'s requirements say this:

> Execution agents are mapped onto threads of execution.

This language is broader than we would like and would seem to include weak things like fibers and SIMD lanes. We should clarify what we mean here.

Additionally, `execution::new_thread` may be unnecessary for C++20, since it was added to satisfy `std::async`'s requirements, and we're not currently planning to enhance `std::async` for C++20.

**Comment by LeeHowes** [comment]
I be conservative I think that `thread` mapping should disallow SIMD, disallow fibers and mean that an agent is on a thread, and own that thread, for the duration of execution.

So wording like:
`An agent A has exclusive ownership of a std::thread for the duration of A and any nested agents that A delegates it's forward progress to.`

If we do keep `new_thread`, then we can extend that:
`An agent A has exclusive ownership of a std::thread for the duration of A and any nested agents that A delegates it's forward progress to. thread_local variables will be newly constructed when A starts, and will be reconstructed for any subsequent agent ordered after A.`
or some similar wording that strongly requires that thread state be "new" for each agent. Actual thread ids may or may not be reusable.

**Comment by jaredhoberock** [comment]
Thanks Lee. I'll prepare a PR for this Friday with your wording for `thread_t` and also strike `new_thread_t`. We can decide on Friday if we want to keep `new_thread_t` after all.

**Comment by AerialMantis** [comment]
Hi everyone,

This wording looks good to me. One comment I would make on the wording for new_thread_t, it may be difficult to use wording which refers to when an execution agent starts because AFAIK the standard doesn’t yet define the lifetime of execution agents. We encountered this same issue when working on the agent local storage paper. Perhaps we could say that thread_local variables must be constructed or reconstructed before A or any execution agent ordered after A on the same std::thread makes forward progress?
Thanks,

Gordon



Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
