### ISSUE TITLE
Map from legacy std::async to a corresponding executor 

### ISSUE THREAD

**Issue by hcedwar** [executors/executors#8]
The current std::async should map onto an executor.  This mapping is currently not specified.

```
template <class F, class... Args>
future<result_of_t<decay_t<F>(decay_t<Args>...)>>
async(launch policy, F&& f, Args&&... args);
```

**Comment by mjgarland** [comment]
To what executor should it map?  Are you assuming a default executor of some sort?

**Comment by hcedwar** [comment]
The minimal proposal should include an executor by which std::async can be implemented.

**Comment by mjgarland** [comment]
If we are talking about new overloads of std::async() that accept executors as parameters, then this is completely true.

If we're talking about legacy overloads that do not accept executors, then I wonder whether you're overstating the requirement.  For the sake of argument, consider a design where we specify a standard thread pool and we want the legacy std::async to run work on that thread pool.  We could, if we chose, specify that the legacy std::async runs on that thread pool.  There are likely other possibilities.

Is it essential that the legacy std::async launches it work via an executor as such, or is it just necessary that it compose in some reasonable fashion with the executor functionality?

**Comment by mjgarland** [comment]
I believe our subsequent discussions concluded that the following is what is needed:

> The standard library should provide a mechanism by which the programmer can obtain an executor `ex` such that `std::async(ex, ...)` is semantically equivalent to calling `std::async(...)` without an executor.

In other words, passing this executor to `std::async` replicates its "legacy" behavior and therefore allows the programmer to start using executors without changing the meaning of their program.  This is of particular value to programmers who are attempting to port code that currently uses `std::async` since it allows them to adopt executors incrementally.

My suggestion is that we create a function in `std::execution` which returns an object, of an implementation-defined type, that is an executor meeting the requirement above.

@hcedwar Could you please check that my description captures the important details?

**Comment by TBBle** [comment]
I think it'd be helpful if such an executor also implemented whatever the standardised behaviour of `std::experimental::future::then` turns out to be (or implementer-decided if this isn't changed from the current wording), for similar reasons. Also similarly for `std::experimental::task_block::run`, and anything else added to the "Control structure interoperation" section.

**Comment by jaredhoberock** [comment]
We decided that we do want to define the interaction between `std::async` and some underlying executor, but that we would not define that interaction in P0443.
