### ISSUE TITLE
Clarify status of TLS

### ISSUE THREAD

**Issue by mjgarland** [executors/executors#83]
The current draft is silent on the connection with TLS.

A simple proposed solution:  Distinguish between executors that

1. Guarantee that agents run on `std::thread`'s and which therefore have the usual TLS.
2. Do not guarantee this and which therefore should be presumed to have no TLS.

This would effectively generalize the existing notion of `HostBased`.

**Comment by ccmysen** [comment]
Do we want to solve TLS on executors? i'm worried that TLS properties will be something more context specific than even host-based (i could be host based but always spawn new threads of execution which would then make TLS useless).

we could consider a trait on this, but i'm not sure that satisfies the need because the actual executing code would need to be TLS aware and thus you would need the tasks to be aware of the context they are executing in. i suspect we'll need a new concept for this.

**Comment by mjgarland** [comment]
No, I don't think we want to solve TLS, nor provide anything like a comprehensive treatment of TLS.  But it might be a good idea to do something minimal that indicates when it does or does not exist.  The thing I outlined above is what I think is the simplest possible thing we can do.

**Comment by ccmysen** [comment]
BTW -- we never resolved this did we come to a conclusion in the meetings as to whether we want to have a discussion of TLS? I think we may have decided to punt.

**Comment by jaredhoberock** [comment]
I think the "execution mapping" properties define the interaction, if any, between execution agents and TLS.
