### ISSUE TITLE
then_execute differs from Concurrency TS V1 semantics

### ISSUE THREAD

**Issue by hkaiser** [executors/executors#96]
The Concurrency TS V1 [N4538](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4538.pdf) specifies (amongst other things) the semantics of `future::then`. This new proposal introduces a variation for `future::then` taking an additional executor argument and the `then_execute` customization point targeted at implementing it. 

Unfortunately, the specified semantics of `future::then` (in N4538) and the proposed semantics of `then_execute` differ in a way prohibiting implementing semantics for `future::then(exec, ...)` conforming to N4538 (if we assume it should be implemented using `then_execute`):

- N4538 specifies for the continuation to be called by passing along the future instance the continuation has been attached to, while `then_execute` should pass along not the future itself, but the value encapsulated by it (or nothing if it is a `future<void>`).
- N4538 specifies for `future::then` to automatically 'unwrap' the resulting future if the continuation returns a `future<R>` itself:

  > When `result_of_t<decay_t<F>(future<R>)>` is `future<R2>`, for some type `R2`, the function returns `future<R2>`. Otherwise, the function returns `future<result_of_t<decay_t<F>(future<R>)>>`. [ Note: The rule above is referred to as implicit unwrapping. Without this rule, the return type of `then` taking a callable returning a `future<R>` would have been `future<future<R>>`. This rule avoids such nested future objects. ... - end note]

  This is especially true as `then_execute` for an `OneWayExecutor` is specified to return ` predecessor.then(std::forward<Function>(f))`, which performs automatic 'unwrapping' (as we're talking about the `future::then` as specified by N4538).

In order for this to be resolved, `then_execute` should be specified to:

- call the continuation function with the future instance instead of the encapsulated value (the extraction of the value can be easily achieved by orthogonal means)
- `then_execute` for an `OneWayExecutor` should not be specified in terms of N4538's `future::then`, for efficiency purposes, `then_execute` should not perform automatic unwrapping.

**Comment by jaredhoberock** [comment]
You're correct that the form of the `then_execute` functions differ from that of the Concurrency TS. I agree that we should pursue consistency, but I'd argue that the current Concurency TS's form of `.then()` is harmful and must be modified in a revision. In a nutshell, `.then()` ought to be formulated so that futures work more like monads as described by Bartosz in [this blog post](https://bartoszmilewski.com/2014/02/26/c17-i-see-a-monad-in-your-future/). In the blog post, Bartosz suggests introducing an additional `.next()` function to monadify future, but I think it would be simpler to just fix the issues with `.then()`.

The problem with passing the future itself as a parameter to the continuation rather than a reference to the wrapped value is that this formulation does not compose with bulk continuations. Unlike continuations executed by a single agent, a bulk continuation's future value must be owned by a group of multiple execution agents. Because common types of futures require unique owners, this implies that the continuation should receive a reference to the object itself as a parameter, rather than the wrapping future. We could insist that single-agent and multi-agent continuations require different type signatures, but it would be simpler to pursue consistency.

I agree that the automatic unwrapping functionality of `.then()` is also a complicating problem. If we agreed that the form of `.then()` is worth reconsidering, then automatic unwrapping should probably be made an orthogonal feature of `std::future` so that there is no interaction with the `.then_execute()` stuff.

**Comment by hkaiser** [comment]
> I agree that we should pursue consistency, but I'd argue that the current Concurency TS's form of  `.then()`  is harmful and must be modified in a revision. In a nutshell, `.then()` ought to be formulated so that futures work more like monads as described by Bartosz in this blog post. In the blog post, 

While I agree that the current interface of the `future` type is not very monadic, I doubt we will be able to change things - too many implementations are out there relying on what has been specified by the Concurrency TS V1. 

But more importantly, I would suggest for this proposal not to rely on changes in other proposals. We can always come back to the executor proposal if we manage to change the way `future` exposes continuations in the future. As mentioned, the current text assumes a certain behavior of `future::then` which is different from how it was specified in the Concurrency TS V1.

> The problem with passing the future itself as a parameter to the continuation rather than a reference to the wrapped value is that this formulation does not compose with bulk continuations.

This is solvable by requiring to pass along a `shared_future<T>` (easily derived from any future type) to the invoked functions.

In our experience it is very valuable to be able to handle exceptions in the continuations. The current executor proposal always assumes that exceptions are handled by the code which is using the executor.

In the end, if a user would like to pass just the value to the continuation, a simple `unwrapped()` facility could be introduced which does nothing but calling `future::get` while passing along the returned value:

    future<T> f = ...;
    future<T> f2 = execution::then_execute(exec, unwrapped([](T val) { ... }), move(f));

**Comment by jaredhoberock** [comment]
> I doubt we will be able to change things - too many implementations are out there relying on what has been specified by the Concurrency TS V1.

We have the ability to change the Concurrency TS, especially functionality we identify as broken. This is the purpose of the TS process. An external proposal our executors project already depends on is the idea of describing the requirements of a `Future` concept. I envision that a better specification of `.then()` would be included as part of these requirements.

> This is solvable by requiring to pass along a shared_future<T> (easily derived from any future type) to the invoked functions.

It's true that `shared_future` could be used to describe the shared predecessor value, but `shared_future` actually solves a different use case with relaxed requirements. The group of sharers of a `shared_future` changes over the `shared_future`'s lifetime -- members may join and leave the group dynamically. This is unlike the group of agents created by `bulk_then_execute()` -- the lifetime of the entire group of sharers is statically known. Capturing information about groups of agents and the objects they collectively own is the purpose of these bulk executor operations.

This static knowledge avoids the inefficiencies created by the more relaxed requirements of `shared_future`'s use case. For example, I would be concerned about the expense of replicating `shared_future`s for each agent of a very large group of agents. I doubt it could be made efficient for all types of executors.

**Comment by jaredhoberock** [comment]
> I'd argue that the current Concurency TS's form of `.then()` is harmful and must be modified in a revision. In a nutshell, .then() ought to be formulated so that futures work more like monads as described by Bartosz in this blog post. In the blog post, Bartosz suggests introducing an additional `.next()` function to monadify future, but I think it would be simpler to just fix the issues with `.then()`.

I guess I should explain why the monadic form of `.then()` actually matters lest I be accused of appealing to category theoretic nonsense :-)

The issue is that Concurrency TS v1's form of `.then()` creates real obstacles to code composition for our executors proposal. The problem appears in applications which need to create continuations with different types of executors.

Our proposal allows each executor type to have an associated future type. So, any code which uses different types of executors may in turn have to manipulate and interoperate with different types of futures. The problem is that Concurrency TS v1's form of `.then()` requires the continuation to receive a `std::future<T>`. In our proposal, not all executors will produce `std::future<T>`.

Clearly, something has to be changed for our proposal's executors to compose with `.then()`. Our proposal could insist that all executors create `std::future<T>`, but I don't think it would be useful.

Another option would be to relax `.then()`'s requirements to insist that the continuation receive a parameter of `executor_future_t<Executor,T>`. However, this would couple the type of `Executor` to the type of the continuation. This would create an obstacle to composition, because the `Executor` type may not be available or known to the author of the continuation. Also, coupling the `Executor` type to the continuation means that the continuation would not be usable with other types of executors. To the degree possible, it should be our goal to maximize interoperability between tasks and different types of executors because this encourages code portability.

There could be other solutions based on wrapping the continuation with another lambda incorporating the `executor_future_t` type, but it seems like the simplest solution is to just uncouple completely the type of the future from the signature of the continuation and instead just receive a `T&` as a parameter. The future doesn't really carry any additional information* the continuation can use anyway. Moreover, it's simpler for the programmer of the continuation to program in terms of the value of interest rather than a wrapped value. 

*The one piece of information this scheme would discard is an exceptional future state. So, we would need to design an alternative scheme for handling errors. One idea taken from other programming languages would be a special form of `.then()` (`.then_try()`, say), which would receive both the continuation function and an error handler function. The idea is that the error handler function would be invoked instead of the continuation function in exceptional cases.

**Comment by hkaiser** [comment]
Thanks again for your explanations. In principle I completely agree with what you're saying, and it is exactly that background which has triggered creating this ticket in the first place: the inconsistencies between `then_execute` and `future::then`.

First of all, in my understanding, the main premise of this executor proposal is to create an underlying layer which should be usable to implement _all_ of the existing and future library facilities requiring the scheduling of tasks (such as parallel algorithms, `async`, `future::then`, etc.). I think this premise should be central to any design decision we apply to this proposal.

Once we agree on this premise, everything else is fairly clear: it directly follows that we should not try to redesign things like `future::then` for the needs of implementing executors but go the opposite route: design the executor API in a way that we can use it to implement `future:;then`. 

While this will require some (substantial) changes to the currently proposed API, it will clear up the air and remove all of the obstacles you outlined above.

**Comment by jaredhoberock** [comment]
Consensus in SG1 seems to be that the Concurrency TS v1's formulation of `.then()` will not be standardized. A separate paper will define the interaction between an enhanced form of `.then()` and `.then_execute()`.
