### ISSUE TITLE
execution::post should be supported by TwoWayExecutor category

### ISSUE THREAD

**Issue by hkaiser** [executors/executors#97]
In the is current wording, the customization point `execution::post` is only supported by the concept `NonBlockingOneWayExecutor`. From our experience, this functionality (fire & forget) is very often required in the context of a `TwoWayExecutor` as well. In this context, we never require for `execution::defer` to be available.

I propose to specify for `execution::post` to be available for `TwoWayExecutor`s, at least by emulation (dispatch to `async_execute` while discarding the returned future).

**Comment by jaredhoberock** [comment]
`post` no longer exists, but we decided that the analogous `oneway`, `never_blocking` behavior will not be supported by `twoway` executors because it was not acceptable to discard futures.

The reason why is because the future may be responsible for boost-blocking and also because the future's destructor could block. It's possible that an elaboration of the `Future` concept could relax this restriction.
